@startuml encryption-flow

title "Encryption Flow"

participant "Platform" as PL #MistyRose
participant Browser #MintCream

PL -> Browser: Request encryption of contacts list

Browser --> Browser: Generate initialization vector (IV)
Browser --> Browser: Encrypt contacts list with **private (symmetric)** key
Browser --> Browser: Encrypt **private (symmetric)** key with **public (asymmetric)** key
Browser --> Browser: Encode encrypted contacts list, private key and IV in **base64**

Browser --> PL: JSON { encrypted contacts list, encrypted (symmetric) private key, IV }

@enduml
