@startuml 001-create-contacts-list

title "001 - Create contacts list"

actor User
participant "Platform" as PL #MistyRose
participant Browser #MintCream
participant "Contacts Manager API" as CNT #Plum
participant "Contacts Manager DB" as CNT_DB #Plum

User -> Browser : Open platform webpage
Browser -> PL : GET /index.html

User -> PL: Clicks create contacts list button

PL -> Browser: Generate private key (symmetric)
Browser --> Browser: Save private key in local database
Browser --> PL: Returns (private) key

PL -> Browser: Generate private and public key (asymmetric)
Browser --> Browser: Save public key in local database
Browser --> Browser: Save private key in local database
Browser --> PL: Returns (public, private) key

PL --> User: Render contacts list page

User -> PL: Fills contact information
PL -> Browser: Save contact in local database

User -> PL: Clicks save contacts button

PL -> Browser: Encrypt local contacts list with private (symmetric) key
PL -> Browser: Encrypt private (symmetric) key with public (asymmetric) key
Browser --> PL: JSON { encrypted contacts list, encrypted (symmetric) private key }

PL -> CNT: POST /contacts JSON { encrypted contacts list, encrypted (symmetric) private key }
CNT --> CNT: Generate document reference
CNT -> CNT_DB: Save encrypted contacts list using document reference
CNT_DB --> CNT: Saved document hash (commit hash)
CNT --> PL: JSON { document reference, document hash }

PL -> Browser: Save document reference and hash in local database
PL --> User: Render saved contacts list information

@enduml
