@startuml 003-view-shared-contacts-list

title "003 - View shared contacts list"

actor "Viewer" as User
participant Browser #MintCream
participant "Platform" as PL #MistyRose
participant "Contacts Manager API" as CNT #Plum
participant "Contacts Manager DB" as CNT_DB #Plum

User -> Browser: Open shared contacts list link
Browser -> PL: GET /<contacts-document-reference>
PL -> CNT: GET /contacts/<contacts-document-reference>
CNT -> CNT_DB: Find encrypted contacts list with specific reference
CNT_DB --> CNT: JSON { encrypted contacts list, encrypted (symmetric) private key }
CNT --> PL: JSON { encrypted contacts list, encrypted (symmetric) private key }

PL --> User: Renders private key prompt
User -> PL: Inserts private key
PL -> Browser: Decrypts symmetric private key
Browser --> PL: Decrypted symmetric private key

PL -> Browser: Decrypt encrypted contacts list
Browser --> PL: Decrypted contacts list

PL --> User: Render contacts list page

@enduml
