@startuml 003-view-shared-contacts-list

title "003 - View shared contacts list"

actor User
participant Browser #MintCream
participant "Platform" as PL #MistyRose
participant "Contacts Manager API" as CNT #Plum
participant "Contacts Manager DB" as CNT_DB #Plum

User -> Browser: Open shared contacts list link
Browser -> PL: GET /<contacts-document-reference>
PL -> CNT: GET /contacts/<contacts-document-reference>
CNT -> CNT_DB: Find encrypted contacts list with specific reference
CNT_DB --> CNT: JSON { encrypted contacts list }
CNT --> PL: JSON { encrypted contacts list }
PL --> User: Renders private key prompt

User -> PL: Chooses generate new key option
PL -> Browser: Generate private and public key
Browser --> Browser: Save public key in local database
Browser --> Browser: Save private key in local database
Browser --> PL: Returns (public, private) key
PL --> User: Render prompt to share public key with contact list owner

@enduml
