@startuml 004-save-contacts-list

title "004 - Save contacts list"

actor User
participant Browser #MintCream
participant "Platform" as PL #MistyRose
participant "Contacts Manager API" as CNT #Plum
participant "Contacts Manager DB" as CNT_DB #Plum

User -> Browser: Open shared contacts list link
Browser -> PL: GET /<contacts-document-reference>
PL -> CNT: GET /contacts/<contacts-document-reference>
CNT -> CNT_DB: Find encrypted contacts list with specific reference
CNT_DB --> CNT: JSON { encrypted contacts list }
CNT --> PL: JSON { encrypted contacts list }
PL --> User: Renders public key prompt

User -> PL: Inserts public key
PL -> Browser: Decrypt contacts list
Browser --> PL: JSON { contacts list }
PL --> User: Render contacts list page

User -> PL: Select save contacts list button
PL -> Browser: Save contacts list in local storage

@enduml
