@startuml 004-save-contacts-list

title "004 - Save contacts list"

actor User
participant Browser #MintCream
participant "Platform" as PL #MistyRose

User -> PL: Select save contacts list button
PL -> Browser: Save contacts list in local storage
Browser --> Browser: Save contacts list in local database using shared link

@enduml
