@startuml 005-import-contacts-list

title "005 - Import contacts list"

actor User
participant "Platform" as PL #MistyRose
participant Browser #MintCream
participant "Contacts Manager API" as CNT #Plum
participant "Contacts Manager DB" as CNT_DB #Plum

User -> PL: Clicks import contacts list button
PL --> User: Renders URL prompt
User -> PL: Inserts URL

PL -> CNT: GET /contacts/<contacts-document-reference>
CNT -> CNT_DB: Find encrypted contacts list with specific reference
CNT_DB --> CNT: JSON { encrypted contacts list }
CNT --> PL: JSON { encrypted contacts list }

PL --> User: Renders public key prompt
User -> PL: Inserts public key

PL -> Browser: Decrypt contacts list
Browser --> PL: JSON { contacts list }

PL -> Browser: Generate private and public key
Browser --> Browser: Save public key in local database
Browser --> Browser: Save private key in local database
Browser --> Browser: Download private key
Browser --> PL: Returns public key

PL -> Browser: Encrypt local database with private key
Browser --> PL: JSON { encrypted contacts list }
PL -> CNT: POST /contacts JSON { encrypted contacts list }
CNT --> CNT: Generate document reference
CNT -> CNT_DB: Save encrypted contacts list using document reference
CNT_DB --> CNT: Saved document hash (commit hash)
CNT --> PL: JSON { document reference, document hash }
PL -> Browser: Save document reference and hash in local database
PL --> PL: Generate shared contacts list link
PL --> User: Render saved contacts list link

@enduml
